version: "3.8"

services:
  personal-site-frontend:
    container_name: personal-site-frontend
    build:
      context: .
    ports:
      - 3001:3001
    networks:
      - nginx_network

networks:
  nginx_network:
    external: true
